//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalyticsScraper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int jbJobID { get; set; }
        public short jbLanguageID { get; set; }
        public int jbClientID { get; set; }
        public Nullable<int> jbLocationID { get; set; }
        public string jbAgentID { get; set; }
        public System.DateTime jbJobDate { get; set; }
        public Nullable<short> jbJobCatID { get; set; }
        public Nullable<short> jbJobLevelLow { get; set; }
        public Nullable<short> jbJobLevelHigh { get; set; }
        public string jbJobTitle { get; set; }
        public Nullable<short> jbIntTitleID { get; set; }
        public string jbDepartment { get; set; }
        public string jbDescription { get; set; }
        public string jbAttachment { get; set; }
        public Nullable<int> jbCandidateID { get; set; }
        public Nullable<System.DateTime> jbFilledDate { get; set; }
        public Nullable<bool> jbOnWeb { get; set; }
        public Nullable<int> jbReportToID { get; set; }
        public string jbReportTo { get; set; }
        public Nullable<byte> jbTotalExams { get; set; }
        public Nullable<short> jbTotalCredits { get; set; }
        public Nullable<short> jbPDCredits { get; set; }
        public Nullable<byte> jbExamMin { get; set; }
        public Nullable<byte> jbExamMax { get; set; }
        public string jbExp1a { get; set; }
        public string jbExp1b { get; set; }
        public string jbExp1c { get; set; }
        public Nullable<decimal> jbSalaryLow { get; set; }
        public Nullable<decimal> jbSalaryHigh { get; set; }
        public Nullable<short> jbSalaryCurrency { get; set; }
        public string jbBonus { get; set; }
        public short jbLife { get; set; }
        public string jbNotes { get; set; }
        public System.DateTime jbLastUpdate { get; set; }
        public Nullable<short> jbCountryID { get; set; }
        public Nullable<short> jbStateID { get; set; }
        public Nullable<short> jbCityID { get; set; }
        public string jbState { get; set; }
        public string jbCity { get; set; }
        public bool jbCityVisible { get; set; }
        public bool jbStateVisible { get; set; }
        public bool jbCountryVisible { get; set; }
        public Nullable<bool> jbEntryLevel { get; set; }
        public string jbReferenceID { get; set; }
        public string jbCreatedBy { get; set; }
        public string jbLastUpdateBy { get; set; }
        public Nullable<System.DateTime> jbPostingFrom { get; set; }
        public Nullable<System.DateTime> jbPostingTo { get; set; }
        public Nullable<System.DateTime> jbOnWebFrom { get; set; }
        public Nullable<System.DateTime> jbOnWebTo { get; set; }
        public Nullable<bool> jbActive { get; set; }
        public Nullable<double> jbSalaryLowUS { get; set; }
        public Nullable<double> jbSalaryHighUS { get; set; }
        public string jbEmail { get; set; }
        public bool jbUnknownClient { get; set; }
        public bool jbFellow { get; set; }
        public bool jbWriting { get; set; }
        public bool jbNotWriting { get; set; }
        public Nullable<decimal> jbTotalSalaryLow { get; set; }
        public Nullable<decimal> jbTotalSalaryHigh { get; set; }
        public string jbRefCode { get; set; }
        public string jbURL { get; set; }
        public Nullable<System.DateTime> jbCreateDate { get; set; }
        public string jbContactInfo { get; set; }
        public bool jbInternship { get; set; }
        public Nullable<bool> jbSkinJobs4Act { get; set; }
        public Nullable<bool> jbSkinNASG { get; set; }
        public Nullable<bool> jbSkinATS { get; set; }
        public string jbKeywordsMetaTag { get; set; }
    }
}
