//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalyticsScraper
{
    using System;
    using System.Collections.Generic;
    
    public partial class plCompanyCategory
    {
        public short ccategoryID { get; set; }
        public string ccategory { get; set; }
        public Nullable<short> ccProductID { get; set; }
        public bool disabled { get; set; }
        public string ccategorydeDE { get; set; }
        public string ccategoryenGB { get; set; }
        public string ccategoryzhCN { get; set; }
        public string ccategoryfrFR { get; set; }
        public string ccategorykoKR { get; set; }
        public string ccategoryjaJP { get; set; }
    }
}
