//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalyticsScraper
{
    using System;
    using System.Collections.Generic;
    
    public partial class plCountry
    {
        public short countryID { get; set; }
        public string country { get; set; }
        public bool disabled { get; set; }
        public short onTop { get; set; }
        public Nullable<short> plcCurrencyID { get; set; }
        public string Country_Code { get; set; }
    }
}
