//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalyticsScraper
{
    using System;
    using System.Collections.Generic;
    
    public partial class plState
    {
        public short stateID { get; set; }
        public string stateCode { get; set; }
        public string stateName { get; set; }
        public Nullable<short> stCountryID { get; set; }
        public bool disabled { get; set; }
    }
}
